# Generated by Django 5.0 on 2026-02-19 22:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fruta",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("citrica", "Cítrica"),
                            ("tropical", "Tropical"),
                            ("vermelha", "Vermelha"),
                            ("climaterica", "Climatérica"),
                            ("outra", "Outra"),
                        ],
                        max_length=20,
                    ),
                ),
                ("data_validade", models.DateField()),
                ("quantidade_estoque", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ativa", "Ativa"),
                            ("vencida", "Vencida"),
                            ("esgotada", "Esgotada"),
                        ],
                        default="ativa",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("data_validade", "nome"),
            },
        ),
    ]
