# Generated by Django 5.0 on 2026-02-12 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loteestoque',
            name='codigo_lote',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='produto',
            name='sku',
            field=models.CharField(blank=True, max_length=40, unique=True),
        ),
    ]
